spring:
  application:
    name: Beck_Spring_MY_Project
  datasource:
    driver-class-name: org.postgresql.Driver
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AKIO
    username: Akiro_93
    password: ThvYgn729183
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


beholder:
  dev-url: http://localhost:8080

  prod-url: https://bezkoder-api.com